---

- name: Update repositories cache and install apt-transport-https package
  apt:
    name: apt-transport-https
    update_cache: yes

- name: Update repositories cache and install ca-certificates package
  apt:
    name: ca-certificates

- name: Update repositories cache and install curl package
  apt:
    name: curl

- name: Update repositories cache and install software-properties-common package
  apt:
    name: software-properties-common

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present 

- name: Add specified repository into sources list.
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    state: present

- name: Update repositories cache and install docker-ce package
  apt:
    name: docker-ce
    update_cache: yes
