apiVersion: v1
kind: Service
metadata:
  labels:
    run: hello-world
  name: hello-world
  namespace: default
spec:
  ports:
  - nodePort: 31283
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: hello-world
  type: LoadBalancer
